### ISSUE TITLE
Leaflet tiles flashes and being selected while drawing to select

### ISSUE THREAD

**Issue by mickeyjohn** [sandropibia/Leaflet.SelectAreaFeature#10]
Hi,
Thanks for sharing the plugin. I found that drawing to select does not work properly in IE 11. I did not test with lower versions of IE yet. It will flash and also select the tiles while drawing arounds layers to select. 
How to reproduce: 
1. Load the example page on IE 11
    URL: https://sandropibia.github.io/Leaflet.SelectAreaFeature/examples/index.html
2. Click on Enable button.
3. Draw around some layers on the map.

Anyone has any ideas how to resolve this? 

Thanks a lot.

**Comment by mickeyjohn** [comment]
I think I found a workaround for this according to here: https://github.com/Leaflet/Leaflet/issues/1821
addHooks: function () {
   // add these two lines
    L.DomUtil.disableImageDrag();
    L.DomUtil.disableTextSelection();
    ....
}

Thanks.

**Comment by sandropibia** [comment]
tested in ms Edge, no issue at all
