### ISSUE TITLE
Selected Areas Remain Upon Map Reload

### ISSUE THREAD

**Issue by gbrokl98** [sandropibia/Leaflet.SelectAreaFeature#13]
Hi, I'm absolutely loving this plug-in! 

However, I'm running into an issue where my selected areas reappear after I've deleted them and the map updates. For example, my deleted selection returns upon zooming in/out on the map. Is there a way to avoid this that I seem to be missing?

**Comment by sandropibia** [comment]
try first to disable the plugin and than delte all area's
