### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by Wurzelkoch** [sandropibia/Leaflet.SelectAreaFeature#15]
Hello,
I see that event handling has been discussed a lot in other issues. However, I'll have to add to this:
I am working with Leaflet 1.9.4 and need to listen to newly finished areas.
When I add another event listener on `mouseup`, I get the behaviour described in issue #14. 
I modified your code according to @alexiscott's proposal in issue #6, now I got it to work.

**Comment by sandropibia** [comment]
you must disable it first
