### ISSUE TITLE
Use Leaflet's Events to fire an event when features might be selected

### ISSUE THREAD

**Issue by alexiscott** [sandropibia/Leaflet.SelectAreaFeature#6]
Hi,
Thanks for the great code. I would like to propose, and I think I saw it mentioned in another of the issues, an event being fired on mouse up. What this would allow for is for anybody using this plugin to easily add a listener to determine when features are added/ removed.

In our use case it's because we have a submit button, to send a list of features over AJAX; that will need to be toggled on/ off depending on whether features are selected.

It should just be a one liner, as events are already added as `Evented`  to the map object in Leaflet. so, `fireEvent` is already available.
````
_doMouseUp: function(ev) {
// Rest of existing code
 this._map.off('mousemove');
         this._map.fireEvent('selectAreaFeature:mouseUp', ev);
````
BTW, if it helps I could submit a pull request for this.
Thanks!

**Comment by adantart** [comment]
Could you please show your changes to accomplish that event management ? ;-)

**Comment by sandropibia** [comment]
event is caught probely now
