### ISSUE TITLE
Events and better match algorithm

### ISSUE THREAD

**Issue by miguelvaz78** [sandropibia/Leaflet.SelectAreaFeature#7]
Great work!

I wold sugest some enhancements that I am using:

1. Add callbacks on draw start and End.

Something like:
(...)
onDrawStart: null,
	_doMouseDown: function(ev) {
        if (this.onDrawStart) this.onDrawStart();
(...)

2. Better match algorith that checks irregular shapes:
(from: https://github.com/substack/point-in-polygon/blob/master/index.js)

isMarkerInsidePolygon: function (marker, poly) {
        var polyPoints = poly.getLatLngs()[0];
        var x = marker.getLatLng().lat, y = marker.getLatLng().lng;

        var inside = false;
        for (var i = 0, j = polyPoints.length - 1; i < polyPoints.length; j = i++) {
            var xi = polyPoints[i].lat, yi = polyPoints[i].lng;
            var xj = polyPoints[j].lat, yj = polyPoints[j].lng;

            var intersect = ((yi > y) != (yj > y))
                && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
            if (intersect) inside = !inside;
        }
        return inside;
    }

3.  Add support for cluster plugin in the getFeaturesSelected function
(...)
           if ((layertype == 'marker' || layertype == 'all') && layer instanceof L.MarkerCluster) {
               var child = layer.getAllChildMarkers();
               if (child) {
                   _.forEach(child, function (m) {
                       if (pol.contains(m.getLatLng()) && insideChecker(m, polLayer)) {
                           layers_found.push(m);
                       }
                   });
               }
           }  
(...)

**Comment by adantart** [comment]
Hi @miguelvaz78 , do you have a pull request (or modifications) to do the events stuff you suggested ? THANK YOU !

**Comment by miguelvaz78** [comment]
[Leaflet.SelectAreaFeature.zip](https://github.com/sandropibia/Leaflet.SelectAreaFeature/files/3819234/Leaflet.SelectAreaFeature.zip)

Hi, here is the verion of teh JS file that I'm using.

Thanks!!

**Comment by adantart** [comment]
Thank you, man ! ;-)
It would be nice to adapt "onDrawEnd", to be able to define when you invoke the class ... because now you are putting the code inside the .js, right ?

**Comment by sandropibia** [comment]
asses your code to the master
