### ISSUE TITLE
Single click bug  and PR

### ISSUE THREAD

**Issue by alexiscott** [sandropibia/Leaflet.SelectAreaFeature#9]
Hi @sandropibia 

I came across what I think is a bug and have added a PR here to fix it: https://github.com/sandropibia/Leaflet.SelectAreaFeature/pull/8
# Steps to reproduce the bug
- Visit https://sandropibia.github.io/Leaflet.SelectAreaFeature/examples/index.html
- Open dev tools console
- Click on "Enable"
- Single click somewhere on the map without moving the mouse afterwards
- Click the get polygon features button
- you will see an error in the console typeError: this._southWest is undefined

**Comment by sandropibia** [comment]
Hello Alex, I can't reproduce it and why should you after enabled it, not to draw anything?

**Comment by sandropibia** [comment]
I'll close this one, for me it is not a issue

**Comment by Wurzelkoch** [comment]
I see the same error even after drawing something, so the button 'get polygon features' in the demo does not work at all.

**Comment by sandropibia** [comment]
you must select some polygons to work and disable it first
